name: Deploy to Azure Blob Static Website

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

concurrency:
  group: deploy-azure
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}   # full JSON

      - name: Ensure subscription
        uses: azure/CLI@v2
        with:
          inlineScript: az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Length check (no secret printed)
      - name: Inspect AZURE_STORAGE_ACCOUNT secret length
        run: |
          ACC='${{ secrets.AZURE_STORAGE_ACCOUNT }}'
          echo "raw_len=$(printf %s "$ACC" | wc -c)"
          ACC_TRIM=$(printf %s "$ACC" | tr -d ' \r\n')
          echo "trim_len=$(printf %s "$ACC_TRIM" | wc -c)"

      # Data-plane sanity (uses AAD auth)
      - name: Quick data-plane test
        uses: azure/CLI@v2
        with:
          inlineScript: |
            set -e
            ACC='${{ secrets.AZURE_STORAGE_ACCOUNT }}'
            ACC_TRIM=$(echo -n "$ACC" | tr -d '\r\n ')
            echo "Static website settings (data plane):"
            az storage blob service-properties show \
              --account-name "$ACC_TRIM" \
              --auth-mode login \
              --query "{enabled:staticWebsite.enabled, index:staticWebsite.indexDocument}" -o table || true
