name: Deploy to Azure Blob Static Website

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

concurrency:
  group: deploy-azure
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Azure login (service principal)
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Ensure correct subscription
        uses: azure/CLI@v2
        with:
          inlineScript: az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: (One-time safe) Ensure static website settings
        uses: azure/CLI@v2
        env:
          ACC: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
        with:
          inlineScript: |
            ACC_TRIM=$(echo -n "$ACC" | tr -d '\r\n ')
            az storage blob service-properties update \
              --account-name "$ACC_TRIM" \
              --auth-mode login \
              --static-website \
              --index-document index.html \
              --404-document 404.html

      - name: Upload site to $web (AAD)
        uses: azure/CLI@v2
        env:
          ACC: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
        with:
          inlineScript: |
            set -e
            ACC_TRIM=$(echo -n "$ACC" | tr -d '\r\n ')
            az storage blob upload-batch \
              --account-name "$ACC_TRIM" \
              --auth-mode login \
              --destination '$web' \
              --source . \
              --overwrite \
              --no-progress \
              --pattern '!**/.git*' \
              --pattern '!**/.github/**'

      - name: List uploaded files (proof)
        uses: azure/CLI@v2
        env:
          ACC: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
        with:
          inlineScript: |
            ACC_TRIM=$(echo -n "$ACC" | tr -d '\r\n ')
            az storage blob list \
              --account-name "$ACC_TRIM" \
              --auth-mode login \
              --container-name '$web' \
              --num-results 50 \
              --query "[].{name:name, modified:properties.lastModified}" -o table
