- name: Ensure subscription
  uses: azure/CLI@v2
  with:
    inlineScript: az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

# Mgmt-plane check (optional): needs Reader; ok to continue on error
- name: (Optional) Show storage account (mgmt plane)
  uses: azure/CLI@v2
  continue-on-error: true
  with:
  inlineScript: |
      ACC='${{ secrets.AZURE_STORAGE_ACCOUNT }}'
      echo "Length (raw):   $(printf %s "$ACC" | wc -c)"
      ACC_TRIM=$(printf %s "$ACC" | tr -d ' \r\n')
      echo "Length (trim):  $(printf %s "$ACC_TRIM" | wc -c)"
      
# Data-plane checks (what upload uses)
- name: Data plane checks
  uses: azure/CLI@v2
  with:
    inlineScript: |
      set -e
      ACC='${{ secrets.AZURE_STORAGE_ACCOUNT }}'
      ACC_TRIM=$(echo -n "$ACC" | tr -d '\r\n ')
      echo "Static website props (data plane):"
      az storage blob service-properties show \
        --account-name "$ACC_TRIM" \
        --auth-mode login \
        --query "{enabled:staticWebsite.enabled, index:staticWebsite.indexDocument}" -o table || true

      echo "List a few blobs from $web (data plane):"
      az storage blob list \
        --account-name "$ACC_TRIM" \
        -c '$web' \
        --num-results 10 \
        --query "[].{name:name, modified:properties.lastModified}" -o table || true
