name: Deploy to Azure Blob Static Website

on:
  push:
    branches: [ main ]      # change if your default branch differs
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}   # the full JSON you saved

      - name: Quick auth test
        uses: azure/CLI@v2
        with:
          inlineScript: |
            echo "Subscription / Tenant check:"
            az account show --query "{subscription:id, tenant:tenantId}" -o tsv

            echo "Storage account exists?"
            az storage account show \
              -n ${{ secrets.AZURE_STORAGE_ACCOUNT }} \
              --query "name" -o tsv

            echo "Static website settings:"
            az storage blob service-properties show \
              --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} \
              --auth-mode login \
              --query "staticWebsite" -o jsonc

      - name: Ensure static website settings
        uses: azure/CLI@v2
        with:
          inlineScript: |
            az storage blob service-properties update \
              --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} \
              --static-website \
              --index-document index.html \
              --404-document 404.html

      # Optional: wipe old files so the container mirrors the repo exactly
      - name: Clean $web container (optional)
        uses: azure/CLI@v2
        with:
          inlineScript: |
            az storage blob delete-batch \
              --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} \
              --auth-mode login \
              -s '$web' --pattern '*'

      - name: Upload site to $web
        uses: azure/CLI@v2
        with:
          inlineScript: |
            az storage blob upload-batch \
              --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} \
              --auth-mode login \
              -d '$web' -s . \
              --overwrite \
              --no-progress \
              --pattern '!**/.git*' \
              --pattern '!**/.github/**'
