name: Deploy to Azure Blob Static Website

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

concurrency:
  group: deploy-azure
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Ensure subscription
        uses: azure/CLI@v2
        with:
          inlineScript: az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # length check catches whitespace/typos in the account secret (won't print the value)
      - name: Inspect AZURE_STORAGE_ACCOUNT secret length
        run: |
          ACC='${{ secrets.AZURE_STORAGE_ACCOUNT }}'
          echo "raw_len=$(printf %s "$ACC" | wc -c)"
          ACC_TRIM=$(printf %s "$ACC" | tr -d ' \r\n')
          echo "trim_len=$(printf %s "$ACC_TRIM" | wc -c)"

      # ✅ Print context to confirm EXACTLY what we will deploy to
     - name: Deploy context (whoami + target)
  uses: azure/CLI@v2
  env:
    CREDS: ${{ secrets.AZURE_CREDENTIALS }}
    ACC:   ${{ secrets.AZURE_STORAGE_ACCOUNT }}
  with:
    inlineScript: |
      set -e
      # pull clientId from the JSON secret (masked in logs)
      CLIENT_ID=$(printf '%s' "$CREDS" | sed -n 's/.*"clientId"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p')
      ACC_TRIM=$(echo -n "$ACC" | tr -d '\r\n ')

      echo "== Azure account context =="
      az account show -o jsonc

      echo "== Service principal clientId (first 12 chars) =="
      echo "${CLIENT_ID}" | cut -c1-12

      echo "== Target storage account name =="
      echo "$ACC_TRIM"

      echo "== Blob endpoint we will hit =="
      echo "https://${ACC_TRIM}.blob.core.windows.net"

      echo "== Target container =="
      echo "\$web"
